# Dataset split
train_split: 0.9
val_split: 0.1

# Training parameters
train_params:
  epochs: 30
  batch: 16
  imgsz: 1280
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  dfl: 1.5
  fl_gamma: 1.5
  label_smoothing: 0.1
  nbs: 64
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 45
  translate: 0.2
  scale: 0.9
  shear: 10
  perspective: 0.001
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.1
  copy_paste: 0.1
  amp: true
  multi_scale: true
  overlap_mask: true
  mask_ratio: 4
  patience: 50